(() => {
  const cfg = window.COOLBEARS_CONFIG || {};
  const $ = s => document.querySelector(s), $$ = s => [...document.querySelectorAll(s)];
  const tr = {
    en:{navMint:'Mint',navReveal:'Reveal',navCollection:'Collection',navRarity:'Rarity',navFaq:'FAQ',connectWallet:'Connect wallet',kicker:'10,000 UNIQUE BEARS • BUILT ON GRAM',heroLine1:'EVERYONE GETS A BEAR.',heroLine2:'NOT EVERYONE GETS A LEGEND.',heroText:'Mint a mystery CoolBear for 7 TON. Trade it immediately. Your real bear and traits are revealed on October 7.',mintNow:'MINT NOW',viewGetgems:'VIEW ON GETGEMS',statPrice:'Mint price',statSupply:'Total supply',statRoyalty:'Royalty',statTx:'Per transaction',speech:'WHO DID YOU GET?',mintKicker:'PRIMARY MINT',mintTitle:'MINT YOUR<br>COOLBEAR',mintText:'Choose between 1 and 50 NFTs. There is no lifetime wallet limit. Each NFT costs 7 TON.',mintNoteLine:'NFTs are tradable immediately after mint.',mintedLabel:'MINTED',quantity:'QUANTITY',total:'TOTAL',connectToMint:'CONNECT WALLET TO MINT',mintFoot:'Up to 50 per transaction • no wallet limit',beforeReveal:'BEFORE REVEAL',revealKicker:'MYSTERY FIRST',revealTitle:'YOUR BEAR<br>IS HIDING.',revealText:'After mint, every NFT shows the official CoolBears GIF. Traits and rarity stay hidden, but the NFT can still be sold, transferred or gifted.',revealLabel:'REVEAL',revealDate:'OCTOBER 7',revealFoot:'On reveal day, the same NFT switches to its final CoolBear and its traits. No reroll.',collectionKicker:'THE COLLECTION',collectionTitle:'DIFFERENT BEARS.<br>SAME VIBE.',collectionText:'10,000 unique combinations built from hand-drawn traits. Clean, weird, rare, legendary — every bear exists once.',rarityKicker:'AFTER REVEAL',rarityTitle:'RARITY WITH<br>REAL WEIGHT.',rarityText:'Every NFT receives a rarity score based on the actual frequency of its final traits across the full 10,000-piece collection.',commonTitle:'The base layer',commonText:'The most frequently appearing traits.',rareTitle:'Harder to find',rareText:'Less common bodies, accessories and combinations.',legendaryTitle:'The legends',legendaryText:'Gold, Crystal, Beer, Robot, Zombie and other top-tier traits.',top50Title:'TOP 50 RAREST COOLBEARS',top50Text:'Hidden until reveal. Ranked by final rarity score.',faqTitle:'QUICK<br>ANSWERS.',faq1q:'Can I sell my NFT before reveal?',faq1a:'Yes. The NFT is transferable and tradable immediately after mint. Before reveal, everyone sees the shared GIF.',faq2q:'When do my traits appear?',faq2a:'On October 7, when final metadata is revealed.',faq3q:'Where can I trade?',faq3a:'After Getgems indexes the collection, owners can list and trade there. The official link will be added after deployment.',faq4q:'How is rarity calculated?',faq4a:'Rarity score is based on the real frequency of each final trait across all 10,000 CoolBears.',footerTag:'Everyone gets a bear. Not everyone gets a legend.',connected:'Wallet connected',mintN:'MINT {n} NFT',connectCancelled:'Wallet connection was cancelled.',tonUnavailable:'TON Connect requires the deployed HTTPS site.',contractPending:'Mint contract will be activated after audited mainnet deployment.'},
    ru:{navMint:'Минт',navReveal:'Раскрытие',navCollection:'Коллекция',navRarity:'Редкость',navFaq:'FAQ',connectWallet:'Подключить кошелёк',kicker:'10 000 УНИКАЛЬНЫХ МЕДВЕДЕЙ • ПРОЕКТ GRAM',heroLine1:'МЕДВЕДЯ ПОЛУЧИТ КАЖДЫЙ.',heroLine2:'ЛЕГЕНДУ — НЕ КАЖДЫЙ.',heroText:'Минть загадочного CoolBear за 7 TON и сразу можешь им торговать. Настоящий медведь и его traits откроются 7 октября.',mintNow:'МИНТ',viewGetgems:'СМОТРЕТЬ НА GETGEMS',statPrice:'Цена минта',statSupply:'Всего',statRoyalty:'Роялти',statTx:'За транзакцию',speech:'КТО ТЕБЕ ПОПАДЁТСЯ?',mintKicker:'ПЕРВИЧНЫЙ МИНТ',mintTitle:'ЗАМИНТЬ СВОЕГО<br>COOLBEAR',mintText:'Выбирай от 1 до 50 NFT за одну транзакцию. Общего лимита на кошелёк нет. Цена одного NFT — 7 TON.',mintNoteLine:'NFT можно перепродавать сразу после минта.',mintedLabel:'ЗАМИНЧЕНО',quantity:'КОЛИЧЕСТВО',total:'ИТОГО',connectToMint:'ПОДКЛЮЧИТЬ КОШЕЛЁК',mintFoot:'До 50 за транзакцию • без лимита на кошелёк',beforeReveal:'ДО РАСКРЫТИЯ',revealKicker:'СНАЧАЛА ТАЙНА',revealTitle:'ТВОЙ МЕДВЕДЬ<br>ПОКА СКРЫТ.',revealText:'После минта каждый NFT показывает официальный GIF CoolBears. Traits и редкость скрыты, но NFT уже можно продавать, передавать или дарить.',revealLabel:'РАСКРЫТИЕ',revealDate:'7 ОКТЯБРЯ',revealFoot:'В день reveal тот же NFT переключится на финального CoolBear и его traits. Без повторного выбора.',collectionKicker:'КОЛЛЕКЦИЯ',collectionTitle:'РАЗНЫЕ МЕДВЕДИ.<br>ОДИН ХАРАКТЕР.',collectionText:'10 000 уникальных сочетаний из нарисованных traits. Каждый медведь существует только один раз.',rarityKicker:'ПОСЛЕ РАСКРЫТИЯ',rarityTitle:'РЕДКОСТЬ,<br>КОТОРАЯ ИМЕЕТ ВЕС.',rarityText:'Каждый NFT получает rarity score по реальной частоте его финальных traits во всей коллекции.',commonTitle:'Базовый уровень',commonText:'Самые часто встречающиеся traits.',rareTitle:'Встречаются реже',rareText:'Более редкие тела, аксессуары и сочетания.',legendaryTitle:'Легенды',legendaryText:'Gold, Crystal, Beer, Robot, Zombie и другие топовые traits.',top50Title:'ТОП-50 САМЫХ РЕДКИХ COOLBEARS',top50Text:'Скрыт до reveal. Рейтинг строится по финальному rarity score.',faqTitle:'КОРОТКИЕ<br>ОТВЕТЫ.',faq1q:'Можно продать NFT до раскрытия?',faq1a:'Да. Сразу после минта NFT можно передавать и продавать. До reveal все видят общий GIF.',faq2q:'Когда появятся traits?',faq2a:'7 октября, после раскрытия финальных metadata.',faq3q:'Где можно торговать?',faq3a:'После индексации коллекции на Getgems владельцы смогут выставлять NFT там.',faq4q:'Как считается редкость?',faq4a:'Rarity score рассчитывается по реальной частоте каждого финального trait.',footerTag:'Медведя получит каждый. Легенду — не каждый.',connected:'Кошелёк подключён',mintN:'МИНТ {n} NFT',connectCancelled:'Подключение кошелька отменено.',tonUnavailable:'TON Connect требует размещённый HTTPS-сайт.',contractPending:'Минт будет активирован после проверенного деплоя контракта в mainnet.'},
    zh:{navMint:'铸造',navReveal:'揭晓',navCollection:'系列',navRarity:'稀有度',navFaq:'常见问题',connectWallet:'连接钱包',kicker:'10,000 只独特酷熊 • GRAM',heroLine1:'每个人都能得到一只熊。',heroLine2:'但不是每个人都能得到传奇。',heroText:'以 7 TON 铸造一只神秘 CoolBear。10 月 7 日揭晓真正的熊和全部属性。',mintNow:'立即铸造',viewGetgems:'在 GETGEMS 查看',statPrice:'铸造价格',statSupply:'总量',statRoyalty:'版税',statTx:'每笔交易',speech:'你会得到哪一只？',mintKicker:'首次铸造',mintTitle:'铸造你的<br>COOLBEAR',mintText:'每次可选择 1–50 个 NFT。每个 NFT 价格为 7 TON。',mintNoteLine:'NFT 铸造后即可立即交易。',mintedLabel:'已铸造',quantity:'数量',total:'总计',connectToMint:'连接钱包开始铸造',mintFoot:'每笔最多 50 个 • 钱包无总量限制',beforeReveal:'揭晓之前',revealKicker:'先保持神秘',revealTitle:'你的熊<br>还在隐藏。',revealText:'铸造后，每个 NFT 都显示官方 CoolBears GIF。属性和稀有度保持隐藏。',revealLabel:'揭晓',revealDate:'10 月 7 日',revealFoot:'揭晓当天，同一个 NFT 会切换为最终 CoolBear 和全部属性。',collectionKicker:'系列',collectionTitle:'不同的熊。<br>同一种感觉。',collectionText:'10,000 个由手绘属性组合而成的独特 CoolBears。',rarityKicker:'揭晓之后',rarityTitle:'真正有意义的<br>稀有度。',rarityText:'每个 NFT 都会根据最终属性的真实出现频率计算稀有度分数。',commonTitle:'基础层级',commonText:'出现频率最高的属性。',rareTitle:'更难找到',rareText:'更少见的身体、配饰和组合。',legendaryTitle:'传奇级',legendaryText:'Gold、Crystal、Beer、Robot、Zombie 等顶级属性。',top50Title:'最稀有的 50 只 COOLBEARS',top50Text:'揭晓前保持隐藏。',faqTitle:'快速<br>解答。',faq1q:'揭晓前可以出售 NFT 吗？',faq1a:'可以。NFT 铸造后即可转移和交易。',faq2q:'什么时候显示属性？',faq2a:'10 月 7 日最终 metadata 揭晓时。',faq3q:'在哪里交易？',faq3a:'Getgems 索引系列后即可交易。',faq4q:'稀有度如何计算？',faq4a:'基于 10,000 个 CoolBears 中最终属性的真实出现频率。',footerTag:'每个人都能得到一只熊，但不是每个人都能得到传奇。',connected:'钱包已连接',mintN:'铸造 {n} 个 NFT',connectCancelled:'已取消钱包连接。',tonUnavailable:'TON Connect 需要已部署的 HTTPS 网站。',contractPending:'主网合约完成检查和部署后将启用铸造。'}
  };
  let lang=localStorage.getItem('coolbears_lang')||'en'; if(!tr[lang])lang='en';
  const t=k=>tr[lang][k]??tr.en[k]??k;
  const qty=$('#qty'),total=$('#total'),wallet=$('#walletBtn'),mint=$('#mintBtn'),note=$('#mintNote'),getgems=$('#getgemsTop'); let connected=false;
  function apply(l){lang=l;localStorage.setItem('coolbears_lang',l);document.documentElement.lang=l==='zh'?'zh-CN':l;$$('[data-i18n]').forEach(e=>e.innerHTML=t(e.dataset.i18n));$$('.bear-lang').forEach(b=>b.classList.toggle('active',b.dataset.lang===l));wallet.textContent=connected?t('connected'):t('connectWallet');mint.textContent=connected?t('mintN').replace('{n}',qty.value):t('connectToMint')}
  $$('.bear-lang').forEach(b=>b.onclick=()=>apply(b.dataset.lang));
  function clamp(){let v=Math.max(1,Math.min(cfg.maxPerTransaction||50,parseInt(qty.value||1)));qty.value=v;total.textContent=(v*(cfg.priceTon||7)).toLocaleString('en-US');if(connected)mint.textContent=t('mintN').replace('{n}',v)}
  $('#minus').onclick=()=>{qty.value=+qty.value-1;clamp()};$('#plus').onclick=()=>{qty.value=+qty.value+1;clamp()};qty.oninput=clamp;
  if(cfg.getgemsUrl){getgems.href=cfg.getgemsUrl;getgems.classList.remove('hidden-link')}
  const mc=Number(cfg.mintedCount||0);$('#minted').textContent=`${mc.toLocaleString('en-US')} / ${(cfg.supply||10000).toLocaleString('en-US')}`;$('#mintBar').style.width=`${Math.min(100,mc/(cfg.supply||10000)*100)}%`;
  async function connect(){if(!window.TON_CONNECT_UI){note.textContent=t('tonUnavailable');return}try{if(!window.tc)window.tc=new TON_CONNECT_UI.TonConnectUI({manifestUrl:new URL('tonconnect-manifest.json',location.href).href});await window.tc.openModal();connected=true;wallet.textContent=t('connected');mint.textContent=t('mintN').replace('{n}',qty.value)}catch(e){note.textContent=t('connectCancelled')}}
  wallet.onclick=connect;mint.onclick=async()=>{if(!connected){await connect();return}note.textContent=t('contractPending')};clamp();apply(lang);
})();
