window.COOLBEARS_CONFIG = {
  officialWebsite: 'https://coolbears-nfts.com',
  network: 'mainnet',
  priceTon: 7,
  supply: 10000,
  royaltyPercent: 7,
  maxPerTransaction: 50,
  revealDate: '2026-10-07',
  preRevealImageCid: 'bafkreigjugpn3qqktlnmztc3dmtxcon357v2qdhugi5vdxkcf6c74bjh5y',
  preRevealMetadataCid: 'bafkreihtd7ouj45unoqkciyri7gqd2ee5trtagoe2zdmd4uhhjckd5aquy',
  preRevealMetadataRootCid: 'bafybeib2xpnz4ke7wus2jesx26v6dtmmhs6zpglowqpt2mabwobawx3d4u',
  collectionMetadataCid: 'bafkreibxu7idtw4s2zwvtvhjhdwxfeahizx3mkn6akqvxus37q2zgcc24e',
  preRevealImageIpfs: 'ipfs://bafkreigjugpn3qqktlnmztc3dmtxcon357v2qdhugi5vdxkcf6c74bjh5y',
  preRevealMetadataIpfs: 'ipfs://bafkreihtd7ouj45unoqkciyri7gqd2ee5trtagoe2zdmd4uhhjckd5aquy',
  preRevealMetadataRootIpfs: 'ipfs://bafybeib2xpnz4ke7wus2jesx26v6dtmmhs6zpglowqpt2mabwobawx3d4u/',
  collectionMetadataIpfs: 'ipfs://bafkreibxu7idtw4s2zwvtvhjhdwxfeahizx3mkn6akqvxus37q2zgcc24e',
  collectionAddress: '',
  mintContractAddress: '',
  treasuryAddress: 'UQBuosyZXH1PI2RBxsUgsjbD6RnsVOMxtCaVKEKMZRpXF9m7',
  royaltyAddress: 'UQBuosyZXH1PI2RBxsUgsjbD6RnsVOMxtCaVKEKMZRpXF9m7',
  getgemsUrl: '',
  demoMode: true
};
