import { test } from 'node:test';
import assert from 'node:assert/strict';
import { generateSigner, signerIdentity, createNoopSigner } from '@metaplex-foundation/umi';
import { toWeb3JsTransaction } from '@metaplex-foundation/umi-web3js-adapters';
import { Keypair } from '@solana/web3.js';
import { getTransactionDecoder } from '@solana/kit';
import { FailedTransactionMetadata } from 'litesvm';
import { fetchCollection, fetchAsset, transfer } from '@metaplex-foundation/mpl-core';
import { fetchCandyMachine, fetchCandyGuard, findCandyGuardPda } from '@metaplex-foundation/mpl-core-candy-machine';
import { environment } from './svm.mjs';
import { buildCollection, buildReserved, buildMachine, buildSaleState, buildMint, buildReveal } from '../chain/builders.mjs';
import { SPEC, CLOSED_DATE } from '../chain/spec.mjs';

test('wallet transport preserves creation-account signature through wallet signing', async () => {
  const {svm,umi,owner}=environment(), collection=generateSigner(umi);
  umi.use(signerIdentity(createNoopSigner(owner.publicKey)));
  const tx=await buildCollection(umi,collection).setBlockhash(svm.latestBlockhash()).buildAndSign(umi);
  const wire=toWeb3JsTransaction(tx);wire.sign([Keypair.fromSecretKey(owner.secretKey)]);
  const result=svm.sendTransaction(getTransactionDecoder().decode(wire.serialize()));
  assert(!(result instanceof FailedTransactionMetadata));
  assert.equal((await fetchCollection(umi,collection.publicKey)).updateAuthority,owner.publicKey);
});

test('Real Core programs: setup, closed sale, mint/payment, transfer, reveal and authority boundaries', async () => {
  const { svm, umi, owner, buyer, send } = environment();
  const collection = generateSigner(umi), reserved = generateSigner(umi), machine = generateSigner(umi);
  const sizes = {};
  sizes.collection = (await send(buildCollection(umi, collection))).bytes;
  sizes.reserved = (await send(buildReserved(umi, reserved, collection.publicKey))).bytes;
  sizes.machine = (await send(await buildMachine(umi, machine, collection.publicKey, 'ab'.repeat(32)))).bytes;
  let col = await fetchCollection(umi, collection.publicKey);
  assert.equal(col.royalties.basisPoints, 700);
  assert.deepEqual(col.royalties.creators, [{ address: owner.publicKey, percentage: 100 }]);
  assert.equal(col.numMinted, 1);
  const cm = await fetchCandyMachine(umi, machine.publicKey);
  assert.equal(cm.data.itemsAvailable, 9999n);
  assert.equal(cm.itemsLoaded, 0);
  assert.equal(cm.data.configLineSettings.__option, 'None');
  const guardAddress = findCandyGuardPda(umi, { base: machine.publicKey });
  let guard = await fetchCandyGuard(umi, guardAddress);
  assert.equal(guard.guards.startDate.value.date, CLOSED_DATE);
  assert.equal(guard.guards.solPayment.value.lamports.basisPoints, 500000000n);
  assert.equal(guard.guards.mintLimit.__option, 'None');
  const asset = generateSigner(umi);
  umi.use(signerIdentity(buyer));
  await send(buildMint(umi, asset, machine.publicKey, collection.publicKey, owner.publicKey), true);
  assert.equal(svm.getAccount(asset.publicKey).exists, false);
  umi.use(signerIdentity(owner));
  await send(buildSaleState(umi, machine.publicKey, owner.publicKey, true));
  umi.use(signerIdentity(buyer));
  const ownerBefore = svm.getBalance(owner.publicKey);
  sizes.mint = (await send(buildMint(umi, asset, machine.publicKey, collection.publicKey, owner.publicKey))).bytes;
  assert.equal(svm.getBalance(owner.publicKey) - ownerBefore, 500000000n);
  let minted = await fetchAsset(umi, asset.publicKey);
  assert.equal(minted.name, 'CoolBears #1 — Hidden Bear');
  assert.equal(minted.uri, 'https://coolbears-nfts.com/metadata/mint/1.json');
  assert.equal(minted.owner, buyer.publicKey);
  assert.equal(minted.updateAuthority.address, collection.publicKey);
  assert.equal((await fetchCandyMachine(umi, machine.publicKey)).itemsRedeemed, 1n);
  await send(buildMint(umi, asset, machine.publicKey, collection.publicKey, owner.publicKey), true);
  assert.equal((await fetchCandyMachine(umi, machine.publicKey)).itemsRedeemed, 1n);
  col = await fetchCollection(umi, collection.publicKey);
  const item = { index: 1, name: 'CoolBears #0001', uri: 'https://example.com/0001.json' };
  assert.throws(() => buildReveal(umi, minted, col, item, SPEC.revealNotBefore - 1));
  // Owning an NFT does not grant permission to replace its art.
  await send(buildReveal(umi, minted, col, item, SPEC.revealNotBefore), true);
  const recipient = generateSigner(umi);
  await send(transfer(umi, { asset: minted, collection: col, newOwner: recipient.publicKey }));
  minted = await fetchAsset(umi, asset.publicKey);
  assert.equal(minted.owner, recipient.publicKey);
  umi.use(signerIdentity(owner));
  sizes.reveal = (await send(buildReveal(umi, minted, col, item, SPEC.revealNotBefore))).bytes;
  minted = await fetchAsset(umi, asset.publicKey);
  assert.equal(minted.name, item.name);
  assert.equal(minted.uri, item.uri);
  assert.equal(minted.owner, recipient.publicKey);
  await send(buildSaleState(umi, machine.publicKey, owner.publicKey, false));
  umi.use(signerIdentity(buyer));
  await send(buildMint(umi, generateSigner(umi), machine.publicKey, collection.publicKey, owner.publicKey), true);
  console.log('Serialized transaction sizes', sizes);
});
