import { test } from 'node:test';
import assert from 'node:assert/strict';
import { createNoopSigner, publicKey } from '@metaplex-foundation/umi';
import { devnetUmi, SITE } from '../solana/builders.mjs';
import { TEST_OWNER, TEST_COLLECTION, TEST_ASSETS, testRevealState, testRevealBuilder } from '../solana/test-reveal.mjs';
const collection = { publicKey: TEST_COLLECTION, updateAuthority: TEST_OWNER, royalties: { basisPoints: 700 } };
const asset = { publicKey: TEST_ASSETS[0], owner: TEST_OWNER, updateAuthority: { type: 'Collection', address: TEST_COLLECTION }, royalties: { basisPoints: 700 }, name: 'CoolBears #0000 — Hidden Bear', uri: `${SITE}/metadata/hidden/0000.json` };
test('Rehearsal only updates name/URI of allowlisted Devnet assets with original owner and royalties', () => {
 const umi = devnetUmi(); umi.identity = createNoopSigner(publicKey(TEST_OWNER)); umi.payer = umi.identity;
 const builder = testRevealBuilder(umi, asset, collection);
 assert.equal(builder.fitsInOneTransaction(umi), true);
 assert.equal(builder.items.length, 1);
 const target = testRevealState(asset, collection);
 assert.equal(target.revealed, false);
 assert.match(target.uri, /\/devnet-reveal\/0000.json$/);
 const done = { ...asset, name: target.name, uri: target.uri };
 assert.equal(testRevealState(done, collection).revealed, true);
 assert.throws(() => testRevealBuilder(umi, done, collection), /уже раскрыт/);
 for (const patch of [{publicKey:TEST_OWNER}, {owner:TEST_COLLECTION}, {uri:'ipfs://private'}, {royalties:{basisPoints:0}}, {name:'CoolBears #0001 — Hidden Bear'}]) assert.throws(() => testRevealBuilder(umi, {...asset,...patch},collection));
 assert.throws(() => testRevealBuilder(umi, asset, {...collection,publicKey:TEST_OWNER}));
 umi.rpc.getEndpoint = () => 'https://api.mainnet-beta.solana.com';
 assert.throws(() => testRevealBuilder(umi,asset,collection));
});
