// Real workerd + persisted SQLite; all signatures/transactions are disposable fixtures.
import assert from 'node:assert/strict';
import {mkdtemp,rm} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import path from 'node:path';
import {buyerGatewayFixture} from './fixtures/buyer-gateway.mjs';
import {buyerGatewayRuntime} from './fixtures/buyer-gateway-runtime.mjs';
const fixture=await buyerGatewayFixture({syntheticOwner:true}),origin='https://buyer-send-runtime.test';
const persist=await mkdtemp(path.join(tmpdir(),'coolbears-buyer-send-runtime-'));
let runtime=await buyerGatewayRuntime({fixture,origin,persist});const cases=[],approvals=new Map();
const dispatch=(route,input)=>runtime.dispatch(origin+'/api/buyer/'+route,{method:'POST',headers:{origin,'content-type':'application/json'},body:JSON.stringify({version:1,nonce:'a'.repeat(64),...input,...(route==='send'?{costApproval:approvals.get(input.order.id)}:route==='review-expiry'?{authorizeExpiryReview:true}:{})})});
const prepare=async input=>{
  const order=fixture.model.createOrder({...input.order,available:9999,assets:input.order.items.map(i=>i.asset)});
  const r=await dispatch('prepare',{order});assert.equal(r.status,200,await r.clone().text());await spaced();
  const partial=fixture.input(input.order.id),checked=await dispatch('check',partial);assert.equal(checked.status,200,await checked.clone().text());
  const quote=(await checked.json()).report.costQuote;approvals.set(input.order.id,{version:1,quote,maxTotalLamports:quote.budget.totalLamports,approvedAt:Date.now()});await spaced();
};
const spaced=()=>new Promise(r=>setTimeout(r,250));
try{
  await runtime.start();const first=fixture.signedInput('runtime-success');
  assert.equal((await dispatch('send',first)).status,403);assert.equal(fixture.calls.length,0);
  cases.push('production-default factory rejects submission before upstream');
  await runtime.stop();runtime=await buyerGatewayRuntime({fixture,origin,persist,allowSubmission:true});await runtime.start();
  await prepare(first);await runtime.stop();await runtime.start();
  cases.push('server-issued cost quote survives full SQLite restart before send');
  const sent=await dispatch('send',first),accepted=await sent.json();assert.equal(sent.status,200,JSON.stringify(accepted));assert.equal(accepted.report.status,'accepted');
  assert.equal(fixture.calls.filter(c=>c.method==='sendTransaction').length,1);cases.push('explicit test opt-in runs signed check and sends exact bytes once');
  await runtime.stop();await runtime.start({BUYER_HELIUS_API_KEY:'rotated-secret-42'});
  const before=fixture.calls.length;assert.equal((await dispatch('send',first)).status,409);assert.equal(fixture.calls.length,before);
  cases.push('SQLite permanent claim survives full runtime restart and secret rotation');
  await runtime.stop();await runtime.start();await spaced();
  const recovered=await dispatch('recover',first),proof=await recovered.json();assert.equal(recovered.status,200);assert.equal(proof.report.status,'verified',JSON.stringify(proof));
  assert.equal(proof.report.proof.signature,accepted.report.signature);assert.equal(fixture.calls.filter(c=>c.method==='sendTransaction').length,1);
  cases.push('read-only recovery verifies finalized exact receipt and Core asset through workerd');
  await spaced();const capped=fixture.signedInput('runtime-cost-ceiling');await prepare(capped);fixture.setMode('fee-rise');
  const costBlocked=await dispatch('send',capped);assert.equal(costBlocked.status,409);assert.equal((await costBlocked.json()).code,'COST_LIMIT_EXCEEDED');
  fixture.setMode('normal');await runtime.stop();await runtime.start();
  assert.equal((await dispatch('send',capped)).status,409);assert.equal(fixture.calls.filter(c=>c.method==='sendTransaction').length,1);
  cases.push('fresh fee above saved ceiling blocks send and cannot release its permanent claim after restart');
  await spaced();fixture.setMode('expiry-clear');
  const expiry=await dispatch('review-expiry',capped),expiryBody=await expiry.json();assert.equal(expiry.status,200,JSON.stringify(expiryBody));
  assert.equal(expiryBody.report.status,'expired');assert.equal(expiryBody.report.retryAuthorized,false);
  await runtime.stop();await runtime.start({BUYER_HELIUS_API_KEY:'rotated-secret-42'});const afterExpiry=fixture.calls.length;
  assert.equal((await (await dispatch('review-expiry',capped)).json()).report.restored,true);
  assert.equal((await dispatch('send',capped)).status,409);assert.equal(fixture.calls.length,afterExpiry);
  cases.push('expiry proof survives SQLite restart and credential rotation; existing send claim is never released');
  await runtime.stop();await runtime.start();fixture.setMode('normal');await spaced();
  const neverSent=fixture.signedInput('runtime-expiry-unsent');await prepare(neverSent);fixture.setMode('expiry-empty');
  const unknown=await dispatch('review-expiry',neverSent);assert.equal((await unknown.json()).report.status,'unknown');
  await spaced();fixture.setMode('expiry-clear');const retired=await dispatch('review-expiry',neverSent);
  assert.equal((await retired.json()).report.status,'expired');
  cases.push('empty payer history refuses expiry while a covered lifetime closes a signed but unsent attempt');
  await runtime.stop();await runtime.start();const noSendCalls=fixture.calls.length;
  assert.equal((await dispatch('send',neverSent)).status,409);assert.equal(fixture.calls.length,noSendCalls);
  assert.equal(fixture.calls.filter(c=>c.method==='sendTransaction').length,1);
  cases.push('retired unsent bytes cannot acquire a first send claim after complete restart');
  fixture.setMode('normal');
  await spaced();const lost=fixture.signedInput('runtime-lost');await prepare(lost);fixture.setMode('send-lost');const failed=await dispatch('send',lost);assert.ok(failed.status>=400);assert.ok(!(await failed.text()).includes('fixture-secret-42'));
  const charged=fixture.calls.length;await runtime.stop();await runtime.start();fixture.setMode('normal');
  assert.equal((await dispatch('send',lost)).status,409);assert.equal((await dispatch('recover',lost)).status,429);assert.equal(fixture.calls.length,charged);
  cases.push('lost upstream reply retains permanent send claim and bounded uncertainty hold after restart');
  assert.deepEqual(runtime.errors,[]);assert.equal((await runtime.ids()).length,1);
  console.log(JSON.stringify({passed:true,cases,upstreamCalls:fixture.calls.length,fixtureSubmissions:fixture.calls.filter(c=>c.method==='sendTransaction').length,transactionsSent:0,liveRpc:false},null,2));
}finally{await runtime.stop();await rm(persist,{recursive:true,force:true});}
